### ISSUE TITLE
setting global composer config

### ISSUE THREAD

**Issue by ghost** [willdurand/puppet-composer#2]
Hello!

Are there any plans on introducing features to support setting global composer config options (the ones that are stored in ~/.composer/config.json)?
Particularly I need to set the github-oauth directive and currently I'm only coming up with hacky solutions :)

**Comment by Ma27** [comment]
seems legit, I'll try figure out whether there's a nice approach

**Comment by Ma27** [comment]
@ghost copying files from your machine into a VM will be difficult. My proposal would be to create another manifest containing the global options and then creating an erb template that would render a custom config.json
