### ISSUE TITLE
default home directory for root user is incorrect

### ISSUE THREAD

**Issue by agargiulo** [willdurand/puppet-composer#26]
### Description

default home directory for root user is incorrect

### Steps to reproduce

```puppet
include composer
::composer::config { 'composer-config':
  ensure => present,
  user     => 'root',
  configs => {
    'github-oauth' => {
      'github.com' => $::magical_oauth_key,
    },
  },
}
```

### Expected behavior

`auth.json` should be generated and stored in `/root/.composer/auth.json`

### Actual behavior
File is created at `/home/root/.composer/auth.json`
```shell
$> ls -l /root/.composer/auth.json
ls: cannot access /root/.composer/auth.json: No such file or directory
$> cat /home/root/.composer/auth.json 
{
    "http-basic": {},
    "github-oauth": {
        "github.com": "TOKEN"},
    "gitlab-oauth": {}
}
```

### Further details

This seems to be where the issue is [manifests/config/entry.pp:25](https://github.com/willdurand/puppet-composer/blob/master/manifests/config/entry.pp#L25-L28)
```puppet
  $home_dir = $custom_home_dir ? {
    undef   => "/home/${user}",
    default => $custom_home_dir,
  }
```

### Related issues

If you're aware of other issues or even issues in other libraries being used by this package then you should reference them here as they may help to solve the issue.

**Comment by Ma27** [comment]
according to https://getcomposer.org/doc/03-cli.md#composer-home the COMPOSER_HOME is in *nix systems by default located at '/home/user'.
The global config files will be stored under this path by default.
If you changed this var, it is possible to use the "home_dir" parameter in order to make composer storing the params at the proper path.

**Comment by Ma27** [comment]
closinf this for now. If you're not happy with my answer then leave a comment and we can continue discussing on it ok? :)

**Comment by agargiulo** [comment]
I understand that part, and I probably shouldn't be using the root user for composer things, but my point is more that root's `$HOME` is different than any other user's by default. `$HOME` for root is `/root/` not `/home/root/.

**Comment by Ma27** [comment]
those global composer configs are some configs for any project of the user who owns this config (e.g. oauth tokens) and as you already mentioned using root for composer projects is a special case.
I think that those edge cases should not be supported natively as they can be solved using '$home_dir' and for users with a different home dir is this parameter created.
Another thing is that there are edge cases of edge cases: the root username is also changeable and supporting the creation of the home dir with this special case would be a overhead that can be solved theough the config parameters.
