### ISSUE TITLE
Failed to apply catalog, Exec[composer-install]: cwd must be a fully qualified path

### ISSUE THREAD

**Issue by mmarseglia** [willdurand/puppet-composer#29]
### Description

Puppet agent errors:
Failed to apply catalog: Parameter cwd failed on Exec[composer-install]: cwd must be a fully qualified path at /etc/puppetlabs/code/environments/production/modules/composer/manifests/init.pp:78

### Steps to reproduce

revision 8b97b4ea42420524b2d8f1824418f07c199c2e13

in a puppet manifest:
include ::composer

### Expected behavior

install composer without errors

### Further details

from facter:
puppetversion	4.3.1

 "architecture" : "x86_64",
  "family" : "RedHat",
  "hardware" : "x86_64",
  "name" : "CentOS",
  "release" : {
    "full" : "7.2.1511",
    "major" : "7",
    "minor" : "2"

**Comment by Ma27** [comment]
ah good catch, I refactored the whole path/cwd shit, but forgot to remove this stupid codeline...

**Comment by Ma27** [comment]
thanks, good catch, fixed for now.
