### ISSUE TITLE
Parameter unless failed, command not qualified and no path specified

### ISSUE THREAD

**Issue by mmarseglia** [willdurand/puppet-composer#31]
### Description

Parameter unless failed on Exec[composer-install]: 'test -s '/usr/local/bin/composer'' is not qualified and no path was specified. Please qualify the command or specify a path.

I tracked it down to line 80 in init.pp in the following exec resource where `test` does not have a fully qualified path.

>   exec { 'composer-install':
>     command => "/usr/bin/wget -O ${composer_full_path} ${target}",
>     user    => $composer_user,
>     unless  => "test -s '${composer_full_path}'",
>     timeout => $download_timeout,
>   }

### Steps to reproduce

  include composer

I resolved it by adding an exec resource reference to set path in my manifest.

> Exec {
>   path => '/bin,/sbin,...',
> }
>
> include composer

  Should the module provide the fully qualified path to the `test` executable used in the exec resource or do I need to include the resource reference?

**Comment by Ma27** [comment]
basically you're right. Although other modules have equal issues (e.g. https://github.com/maestrodev/puppet-wget/blob/master/manifests/fetch.pp#L101) and this issue is usually hidden, so it needs to be fixed.
