### ISSUE TITLE
make installer more configurable

### ISSUE THREAD

**Issue by Ma27** [willdurand/puppet-composer#35]
currently we're enforcing that the user uses wget as install method.
The install process should be refactored, so curl and wget are possible

**Comment by graemedavidson** [comment]
+1

adding some flag for the following wget option would be appreciated ''--no-check-certificate". Not looked into origins of setting this but seems to remove the need to use https in the first place.

**Comment by Ma27** [comment]
good point, will consider this when working on that ticket :)

**Comment by Ma27** [comment]
Not relevant enough IMHO. We may want to add extraFlags support, but that's it.
