### ISSUE TITLE
Error with getcomposer.org SSL Certificate on Debian 8

### ISSUE THREAD

**Issue by epieddy** [willdurand/puppet-composer#37]
### Description

While trying to wget 'https://getcomposer.org/composer.phar' on Debian 8, you get an error because of the SSL certificate of getcomposer.org. The authority path for this certificate is not installed by default on Debian 8:

`Notice: /Stage[main]/Composer/Exec[composer-install]/returns: converted 'https://getcomposer.org/composer.phar' (ANSI_X3.4-1968) -> 'https://getcomposer.org/composer.phar' (UTF-8)
Notice: /Stage[main]/Composer/Exec[composer-install]/returns: --2016-10-07 10:46:05--  https://getcomposer.org/composer.phar
Notice: /Stage[main]/Composer/Exec[composer-install]/returns: Resolving getcomposer.org (getcomposer.org)... 87.98.253.108, 2001:41d0:a:7b19::2
Notice: /Stage[main]/Composer/Exec[composer-install]/returns: Connecting to getcomposer.org (getcomposer.org)|87.98.253.108|:443... connected.
Notice: /Stage[main]/Composer/Exec[composer-install]/returns: ERROR: The certificate of 'getcomposer.org' is not trusted.
Notice: /Stage[main]/Composer/Exec[composer-install]/returns: ERROR: The certificate of 'getcomposer.org' hasn't got a known issuer.
Error: /usr/bin/wget -O /usr/local/bin/composer https://getcomposer.org/composer.phar returned 5 instead of one of [0]
Error: /Stage[main]/Composer/Exec[composer-install]/returns: change from notrun to 0 failed: /usr/bin/wget -O /usr/local/bin/composer https://getcomposer.org/composer.phar returned 5 instead of one of [0]
Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]: Dependency Exec[composer-install] has failures: true`

### Steps to reproduce

class {'::composer':
        command_name => 'composer',
        target_dir   => '/usr/local/bin',
      }

### Further details

Debian 8.6
puppet-composer 1.2.1

**Comment by epieddy** [comment]
You can add the --no-check-certificate to the wget command :

`exec { 'composer-install':
    command => "/usr/bin/wget --no-check-certificate -O ${composer_full_path} ${target}",
    user    => $composer_user,
    creates => $composer_full_path,
    timeout => $download_timeout,
    require => Package['wget'],
  }`

An even better solution would be to migrate to the new official way to install composer : https://getcomposer.org/download/

**Comment by Ma27** [comment]
seems legit. Would you like to create a PR for that?

**Comment by Ma27** [comment]
just adding a `1.2.2` milestone here to have an milestone for each version which makes retracing of fixed issues in the last versions easier.
