### ISSUE TITLE
target_dir creates file in two locations

### ISSUE THREAD

**Issue by den-is** [willdurand/puppet-composer#39]
### Description

When indicating  custom `target_dir` module installs to that directory and additionally to /bin

### Steps to reproduce

Classify node with (in my case it is centos7)

```ruby
class { '::composer':
  command_name => 'composer',
  target_dir   => '/usr/bin'
}
```
```shell
# whereis composer
composer: /usr/bin/composer
```
```shell
# which composer
/bin/composer
```
### Expected behavior

Should locate composer in `/usr/bin` only

### Further details
For test: Prior to classifying node with composer i'm deleting files in both location `/bin` and `/usr/bin`

After classification finished files again appear in both locations

**Comment by Ma27** [comment]
hmm, that sounds odd.

could you please show me which kind of files are located in the `/bin` and `/usr/bin` directory are (`ls -l` gives details about that).
Not sure which might cause such an odd behavior.

**Comment by den-is** [comment]
```
# ls -l /bin/composer
-rwxr-xr-x. 1 root root 1803065 Dec  3 23:33 /bin/composer
# ls -l /usr/bin/composer
-rwxr-xr-x. 1 root root 1803065 Dec  3 23:33 /usr/bin/composer
```

Yeah it looks very odd.
I have looked in your module code, and haven't found thing which places composer in both locations.Especially when your are not `php installing` but just downloading binary.
Probably something wrong with `wget` hmm.

As I said for test purposes I'm deleting both files before calling composer class, both files created again after composer class executed. nothing shown in puppet output

```
# rm -f /bin/composer /usr/bin/composer
# ll /bin/composer
ls: cannot access /bin/composer: No such file or directory
# ll /usr/bin/composer
ls: cannot access /usr/bin/composer: No such file or directory
# puppet agent -t -d
Debug: Exec[composer-install](provider=posix): Executing '/usr/bin/wget --no-check-certificate -O /usr/bin/composer https://getcomposer.org/composer.phar'
Debug: Executing with uid=root: '/usr/bin/wget --no-check-certificate -O /usr/bin/composer https://getcomposer.org/composer.phar'
Notice: /Stage[main]/Composer/Exec[composer-install]/returns: executed successfully
Debug: /Stage[main]/Composer/Exec[composer-install]: The container Class[Composer] will propagate my refresh event
Notice: /Stage[main]/Composer/File[/usr/bin/composer]/mode: mode changed '0644' to '0755'
Notice: /File[/usr/bin/composer]/seluser: seluser changed 'unconfined_u' to 'system_u'
Debug: /Stage[main]/Composer/File[/usr/bin/composer]: The container Class[Composer] will propagate my refresh event
Debug: /Stage[main]/Composer/File[/usr/bin/composer]: The container Class[Composer] will propagate my refresh event
Debug: Class[Composer]: The container Stage[main] will propagate my refresh event
```

**Comment by Ma27** [comment]
have you tested it on a fresh machine? (e.g. with vagrant)

Don't have much time yet, will have a look at it tonight...

**Comment by Ma27** [comment]
ok, reproduced it on a CentOS 7.0 box.
IT seems as everything works fine on Ubuntu 16.04 and this behavior occurs on CentOs only.
Will reserve 1h on the next weekend to do further investigation (not really sure what's causing this, so I might need a bit more time)

**Comment by den-is** [comment]
thanks for your time and attention!
my test box was kinda "fresh" install.
had no much time as well for completely fresh setup via vagrant especially on several different distributions.
was trying to find if composer run with root users causes creation of similar binary in /bin.
crazy that it is not symlink
I was not able to find such behavior description in official docs

**Comment by Ma27** [comment]
well the bug seems to appear on CentOS only.
Since I managed to reproduce it, I hope that I'll find the cause for that on the weekend.

**Comment by Ma27** [comment]
not sure, but I think that I found the cause.
In CentOS 7 (tested it with `7.0.1406 ` using the `puppetlabs/centos-7.0-64-puppet` box) they're symlinking /bin to /usr/bin (not talking about the executables, but about the entire directory) and according to [this](https://www.centos.org/forums/viewtopic.php?t=49330) it's intended.

The reason why you're experiencing this is due to the fact that you're using `/usr/bin` as target dir (which is symlinked to `/bin`) and not `/usr/local/bin`.
As this is a core setting of CentOS and I didn't notice any further issues I don't think that we really need a fix for that.
I'd add a warning to the `README.md` and that's it.

**Comment by den-is** [comment]
Oh yeah, totally forgot about that feature of CentOS 7.
Thanks for your time one more time!
