### ISSUE TITLE
User and Group should be configurable

### ISSUE THREAD

**Issue by jg-development** [willdurand/puppet-composer#4]
the composer::project always uses the root account to exec the install and update from composer.
It should be possible to choose the user and group with the composer::project.
Perhaps a default with www-data/httpd should be choosen.

**Comment by Ma27** [comment]
https://github.com/willdurand/puppet-composer/blob/master/manifests/init.pp#L31
you can choose a user. If no user is provided, the root account will be used.

**Comment by Ma27** [comment]
wait, didn't see that groups are not supported.
