### ISSUE TITLE
adding config with/to root user, creates /home/root

### ISSUE THREAD

**Issue by den-is** [willdurand/puppet-composer#40]
### Description
Really minor issue.
Adding config to user `root` without specifying `home_dir` creates `/home/root` and places config there.

### Steps to reproduce

classify node with:
```ruby
class { '::composer': }

::composer::config { 'composer-root-config':
  ensure   => present,
  user     => 'root',
  configs  => {
    'github-oauth' => {
      'github.com' => 'key'
    },
  },
  require  => Class['::composer']
}
```

### Expected behavior
Root is pretty default user in every linux distribution.
And there is fact `root_home` with proper value
It is possible to get users home dir via puppet.

Probably I can do PR if this is accepted behavior :)

**Comment by Ma27** [comment]
seems to be related to #26.

I'm (still) against this change as you usually don't use composer as root (it's installed with root permissions, but everyone can use the executable).

This `/home/${user}` is just a quick hack to avoid that everyone needs to adjust a home directory although the user can be retrieved easily.
But I don't think that adding more and more of these junctions in the logic makes it unnecessary bloated.

Furthermore this behavior is documented here (https://github.com/willdurand/puppet-composer#global-composer-configs).

**Comment by Ma27** [comment]
will close this for now.
If I misunderstood you or you don't agree with me, feel free to comment here (of course I'm open to continue a discussion about that here)

**Comment by den-is** [comment]
nah, np
it was just suggestion
In general i'm not using config too much.
I've discovered it suddenly, using your module in my wrapper module.
decided to test config functionality and was unable to find config in appropriate place; then recalled about home_dir argument.
