### ISSUE TITLE
Specify the composer version

### ISSUE THREAD

**Issue by DracoBlue** [willdurand/puppet-composer#5]
If I got it right, you can only install the latest version of composer. So if an update of composer is released, puppet does not know what version is installed or if it should update it, does it?

Currently it might not be necessary to specify a specific version of composer. But it should be possible to stick to a specific version of composer or at least force the updated to the latest composer version somehow.

Any plans on integrating this?

**Comment by Ma27** [comment]
seems legit :+1:

**Comment by DracoBlue** [comment]
:+1:

Am Sonntag, 17. Januar 2016 schrieb Maximilian Bosch :

> Closed #5 <https://github.com/willdurand/puppet-composer/issues/5> via #12
> <https://github.com/willdurand/puppet-composer/pull/12>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willdurand/puppet-composer/issues/5#event-517227331>.
>


-- 

  http://dracoblue.net

**Comment by Ma27** [comment]
please note that this change is not released yet. There are some more tickets in the queue for the 1.2 release and if they're fixed, you'll see this enhancement in a stable release :)
